{
    "current_index": 0,
    "name": "DAY3-N",
    "problems": [
        {
            "cases": [
                {
                    "expected": "",
                    "expected_output_filename": "",
                    "input": "",
                    "input_filename": "",
                    "name": "试题案例1"
                },
                {
                    "expected": "-20",
                    "expected_output_filename": "",
                    "input": "3\n10 20 30\n3\n30 20 10",
                    "input_filename": "",
                    "name": "试题案例2"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:18px; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">考试成绩I</p></body></html>",
            "memory_limit": 512,
            "memory_limit_unit": 1,
            "name": "考试成绩I",
            "time_limit": 1,
            "time_limit_unit": 0,
            "url": ""
        },
        {
            "cases": [
                {
                    "expected": "",
                    "expected_output_filename": "",
                    "input": "",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:18px; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">考试成绩II</p></body></html>",
            "memory_limit": 512,
            "memory_limit_unit": 1,
            "name": "考试成绩II",
            "time_limit": 1,
            "time_limit_unit": 0,
            "url": ""
        },
        {
            "cases": [
                {
                    "expected": "",
                    "expected_output_filename": "",
                    "input": "",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:18px; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">狼人杀</p></body></html>",
            "memory_limit": 512,
            "memory_limit_unit": 1,
            "name": "狼人杀",
            "time_limit": 1,
            "time_limit_unit": 0,
            "url": ""
        },
        {
            "cases": [
                {
                    "expected": "6",
                    "expected_output_filename": "",
                    "input": "7\n1 1 2 3 8 5 8",
                    "input_filename": "",
                    "name": "试题案例1"
                },
                {
                    "expected": "5",
                    "expected_output_filename": "",
                    "input": "10\n2 -1 0 3 -1 -1 5 8 13 -2",
                    "input_filename": "",
                    "name": "试题案例2"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:18px; font-weight:400; font-style:normal;\">\n<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">斐波那契序列</p></body></html>",
            "memory_limit": 512,
            "memory_limit_unit": 1,
            "name": "斐波那契序列",
            "time_limit": 1,
            "time_limit_unit": 0,
            "url": ""
        }
    ]
}
