{
    "current_index": 8,
    "name": "试题集2",
    "problems": [
        {
            "answer_program": "D:/CODE/YbtCode/.DAY5/A1_B3612.cpp",
            "cases": [
                {
                    "expected": "10\n5\n",
                    "expected_output_filename": "",
                    "input": "4\n4 3 2 1\n2\n1 4\n2 3\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 128,
            "memory_limit_unit": 1,
            "name": "B3612 【深进1.例1】求区间和",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/B3612"
        },
        {
            "answer_program": "D:/CODE/YbtCode/.DAY5/A2_P2367.cpp",
            "cases": [
                {
                    "expected": "2\n",
                    "expected_output_filename": "",
                    "input": "3 2\n1 1 1\n1 2 1\n2 3 1\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 125,
            "memory_limit_unit": 1,
            "name": "P2367 语文成绩",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P2367"
        },
        {
            "cases": [
                {
                    "expected": "2\n3\n2 2\n5\n2 3\n7\n2 2 2\n3 3\n2 5\n",
                    "expected_output_filename": "",
                    "input": "9\n2\n3\n4\n5\n6\n7\n8\n9\n10\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 512,
            "memory_limit_unit": 1,
            "name": "B3715 分解质因子 2",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/B3715"
        },
        {
            "cases": [
                {
                    "expected": "3 30\n",
                    "expected_output_filename": "",
                    "input": "6 15\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 128,
            "memory_limit_unit": 1,
            "name": "B3634 最大公约数和最小公倍数",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/B3634"
        },
        {
            "answer_program": "D:/CODE/YbtCode/.DAY5/F_B3614.cpp",
            "cases": [
                {
                    "expected": "2\n1\nAnguei!\nEmpty\nAnguei!\n0\n",
                    "expected_output_filename": "",
                    "input": "2\n5\npush 2\nquery\nsize\npop\nquery\n3\npop\nquery\nsize\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 512,
            "memory_limit_unit": 1,
            "name": "B3614 【模板】栈",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/B3614"
        },
        {
            "answer_program": "D:/CODE/YbtCode/.DAY5/G_B3631.cpp",
            "cases": [
                {
                    "expected": "75\n99\n",
                    "expected_output_filename": "",
                    "input": "6\n1 1 99\n1 99 50\n1 99 75\n2 99\n3 75\n2 1\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 128,
            "memory_limit_unit": 1,
            "name": "B3631 单向链表",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/B3631"
        },
        {
            "answer_program": "D:/CODE/YbtCode/.DAY5/H_P1305.cpp",
            "cases": [
                {
                    "expected": "abdicj\n",
                    "expected_output_filename": "",
                    "input": "6\nabc\nbdi\ncj*\nd**\ni**\nj**\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 125,
            "memory_limit_unit": 1,
            "name": "P1305 新二叉树",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P1305"
        },
        {
            "answer_program": "D:/CODE/YbtCode/.DAY5/I_P2249.cpp",
            "cases": [
                {
                    "expected": "1 2 -1\n",
                    "expected_output_filename": "",
                    "input": "11 3\n1 3 3 3 5 7 9 11 13 15 15\n1 3 6\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 125,
            "memory_limit_unit": 1,
            "name": "P2249 【深基13.例1】查找",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P2249"
        },
        {
            "answer_program": "D:/CODE/YbtCode/.DAY5/J_B3628.cpp",
            "cases": [
                {
                    "expected": "601\n",
                    "expected_output_filename": "",
                    "input": "3\n-100 -200 -300\n",
                    "input_filename": "",
                    "name": "试题案例1"
                },
                {
                    "expected": "501\n",
                    "expected_output_filename": "",
                    "input": "5\n-200 -300 1000 -100 -100\n",
                    "input_filename": "",
                    "name": "试题案例2"
                }
            ],
            "description": "",
            "memory_limit": 128,
            "memory_limit_unit": 1,
            "name": "B3628 机器猫斗恶龙",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/B3628"
        },
        {
            "answer_program": "D:/CODE/YbtCode/.DAY5/E_P1305.cpp",
            "cases": [
                {
                    "expected": "2\n3\n5\n7\n11\n",
                    "expected_output_filename": "",
                    "input": "100 5\n1\n2\n3\n4\n5\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\np, li { white-space: pre-wrap; }\n</style></head><body style=\" font-family:'Microsoft YaHei UI'; font-size:18px; font-weight:400; font-style:normal;\">\n<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>",
            "memory_limit": 512,
            "memory_limit_unit": 1,
            "name": "P3383 【模板】线性筛素数",
            "time_limit": 3000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P3383"
        }
    ]
}
