{
    "current_index": 7,
    "name": "试题集2",
    "problems": [
        {
            "cases": [
                {
                    "expected": "4\n",
                    "expected_output_filename": "",
                    "input": "8 15\n20 130\n120 3\n150 2\n110 7\n180 1\n50 8\n200 0\n140 3\n120 2\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 125,
            "memory_limit_unit": 1,
            "name": "P1478 陶陶摘苹果（升级版）",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P1478"
        },
        {
            "cases": [
                {
                    "expected": "3\n",
                    "expected_output_filename": "",
                    "input": "4 1\n1 1 2 3\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 125,
            "memory_limit_unit": 1,
            "name": "P1102 A-B 数对",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P1102"
        },
        {
            "cases": [
                {
                    "expected": "14\n",
                    "expected_output_filename": "",
                    "input": "4 2 3\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 125,
            "memory_limit_unit": 1,
            "name": "P2239 [NOIP 2014 普及组] 螺旋矩阵",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P2239"
        },
        {
            "cases": [
                {
                    "expected": "3\n",
                    "expected_output_filename": "",
                    "input": "5 6\n4 2 4 5 1\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 125,
            "memory_limit_unit": 1,
            "name": "P1181 数列分段 Section I",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P1181"
        },
        {
            "cases": [
                {
                    "expected": "114\n",
                    "expected_output_filename": "",
                    "input": "3 7\n232\n124\n456\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 128,
            "memory_limit_unit": 1,
            "name": "P2440 木材加工",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P2440"
        },
        {
            "cases": [
                {
                    "expected": "60\n",
                    "expected_output_filename": "",
                    "input": "12 5\n2 5 3 1 3 2 4 1 1 5 4 3\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 512,
            "memory_limit_unit": 1,
            "name": "B4098 [CSP-X2022 山东] 动物园",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/B4098"
        },
        {
            "cases": [
                {
                    "expected": "3\n",
                    "expected_output_filename": "",
                    "input": "5 1 5\n3 3 1 2 5\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 128,
            "memory_limit_unit": 1,
            "name": "P1135 奇怪的电梯",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P1135"
        },
        {
            "cases": [
                {
                    "expected": "2 3 5 4 7 8\n",
                    "expected_output_filename": "",
                    "input": "6 3\n5 2 3 8 7 4\n",
                    "input_filename": "",
                    "name": "试题案例1"
                }
            ],
            "description": "",
            "memory_limit": 128,
            "memory_limit_unit": 1,
            "name": "P1750 出栈序列",
            "time_limit": 1000,
            "time_limit_unit": 1,
            "url": "https://www.luogu.com.cn/problem/P1750"
        }
    ]
}
